config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
  	render html: "Hello, world"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home # This is the one that generates views
  end

  def help
  end

  def about    
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_accessor :name, :email, :password
  
  def new
    def _initialize(atributes = {})
      @name = atributes[:name]
      @email = atributes[:email]
      @password = atributes[:password]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = "")
    base_title = "Ruby Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
<small>
  The <a href="google.com">Sample App</a>
  By <a href="google.com">Tomás Guzmán</a>
</small>

<nav>
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
    <li>
      <a href="http://www.google.com">News</a>
    </li>
  </ul>
</nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container"> 
    <%= link_to "la mejor app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
	You want some <i>about</i>? Go fuck yourself
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
	You want some <i>contact</i>? Go fuck yourself
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
	You want some <i>help</i>? Go fuck yourself
</p>

app/views/static_pages/home.html.erb
<div class="jumbotron text-center">
  <h1>La <code>mejor</code> aplicación</h1>

  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <h2>Bienvenido</h2>
        <p>Estás en este momento en la <code>mejor</code> página web de todas</p>
        <p>Esto es una garantía</p>
      </div>
  
      <div class="col-sm-4">
        <h2>Subscríbete</h2>
        <p>Es sencillo</p>
        <%= link_to "Subscríbete ahí", signup_path, class: "btn btn-lg btn-primary" %>
      </div>

      <div class="col-sm-4">
        <h2>Deberías</h2>
        <p>De pana deberías meterte en esta página más</p>
        <p>Es la <code>mejor</code> página de todas</p>
      </div>
    </div>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails logo"), "http://google.com" %>

  <blockquote>
    <p>Te vas a tener que mamar un webo</p>
    <footer>Tomás Guzmán</footer>
  </blockquote>
</div>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a sign up page for users.</p>